import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

// Run 'npm install cheerio' before using this script
// Usage: node scripts/scraper-bot.mjs https://www.competitor-taxi.com

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

async function scrapeCompetitor(targetUrl) {
    console.log(`\n🤖 Haram Taxi Scraper Bot Initiated...`);
    console.log(`📡 Target: ${targetUrl}`);

    try {
        // Dynamic import for dependencies so it fails gracefully
        let cheerio, axios, https;
        try {
            cheerio = await import('cheerio');
            axios = (await import('axios')).default;
            https = await import('https');
        } catch (e) {
            console.error('\n❌ ERROR: Missing dependencies.');
            console.error('👉 Please run: npm install cheerio axios');
            process.exit(1);
        }

        // Configure HTTPS Agent to ignore SSL certificate errors (common on competitor sites)
        const httpsAgent = new https.Agent({
            rejectUnauthorized: false,
        });

        // 1. Fetch the raw HTML using Axios (Bypasses Node 'fetch' bugs & SSL issues)
        const response = await axios.get(targetUrl, {
            httpsAgent: httpsAgent,
            headers: {
                'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.51 Safari/537.36',
                'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8',
                'Accept-Language': 'en-US,en;q=0.9',
                'Accept-Encoding': 'gzip, deflate, br',
                'Connection': 'keep-alive',
                'Upgrade-Insecure-Requests': '1',
                'Sec-Fetch-Dest': 'document',
                'Sec-Fetch-Mode': 'navigate',
                'Sec-Fetch-Site': 'none',
                'Sec-Fetch-User': '?1',
                'Cache-Control': 'max-age=0'
            },
            timeout: 10000,
            validateStatus: function (status) {
                return status < 500; // Resolve only if the status code is less than 500
            }
        });

        const htmlText = response.data;
        console.log(`✅ Successfully fetched ${htmlText.length} bytes of data.`);

        const $ = cheerio.load(htmlText);

        // 2. Extract SEO Metadata
        const title = $('title').text().trim();
        const metaDesc = $('meta[name="description"]').attr('content') || 'No description found';
        const metaKeywords = $('meta[name="keywords"]').attr('content') || 'No keywords found';
        
        // 3. Extract Headings (H1, H2, H3)
        const h1s = [];
        $('h1').each((i, el) => h1s.push($(el).text().trim().replace(/\s+/g, ' ')));

        const h2s = [];
        $('h2').each((i, el) => h2s.push($(el).text().trim().replace(/\s+/g, ' ')));

        const h3s = [];
        $('h3').each((i, el) => h3s.push($(el).text().trim().replace(/\s+/g, ' ')));

        // 4. Extract Pricing Intelligence (Look for "SAR", "Riyal", "$", numbers)
        const pricingSentences = new Set();
        $('p, li, td, span').each((i, el) => {
            const text = $(el).text().trim().replace(/\s+/g, ' ');
            if (/(SAR|Riyal|SR|\$|Cost|Price|Rate\s*\d+)/i.test(text) && text.length < 200 && text.length > 5) {
                pricingSentences.add(text);
            }
        });

        // 5. Extract Features & Services (Bullet points usually)
        const features = [];
        $('ul li').each((i, el) => {
            const text = $(el).text().trim().replace(/\s+/g, ' ');
            if (text.length > 10 && text.length < 150) {
                features.push(text);
            }
        });

        // 6. Format the Intelligence Report
        const urlObj = new URL(targetUrl);
        const domainName = urlObj.hostname.replace('www.', '');
        const dateStr = new Date().toISOString().split('T')[0];
        
        const report = `
# 🕵️ Competitor Intelligence Report: ${domainName}
**Target URL:** ${targetUrl}
**Date Scraped:** ${dateStr}

## 1. SEO Profile
*   **Target Title:** ${title}
*   **Meta Description:** ${metaDesc}
*   **Keywords:** ${metaKeywords}

## 2. Content Structure (What are they focusing on?)
### Core Topic (H1)
${h1s.map(h => `- ${h}`).join('\n')}

### Sub-Topics (H2)
${h2s.slice(0, 15).map(h => `- ${h}`).join('\n')}

### Granular Angles (H3)
${h3s.slice(0, 15).map(h => `- ${h}`).join('\n')}

## 3. Pricing Intelligence 💰
(Extracted mentions of rates, costs, or SAR)
${Array.from(pricingSentences).slice(0, 15).map(p => `- ${p}`).join('\n') || '*No explicit pricing data found.*'}

## 4. Key Selling Features 🎯
${features.slice(0, 20).map(f => `- ${f}`).join('\n')}

---
*Report generated by Haram Taxi Automated Scraper Bot.*
`;

        // 7. Save to file
        const outputDir = path.join(__dirname, 'output');
        if (!fs.existsSync(outputDir)) {
            fs.mkdirSync(outputDir);
        }

        const safeFilename = domainName.replace(/[^a-z0-9]/gi, '_').toLowerCase();
        const outputPath = path.join(outputDir, `${safeFilename}_report.md`);
        
        fs.writeFileSync(outputPath, report.trim());

        console.log(`\n🎉 Scraping Complete!`);
        console.log(`📄 Intelligence report saved to: ${outputPath}`);

    } catch (error) {
        console.error(`\n❌ Bot failed to scrape ${targetUrl}`);
        console.error(`Reason: ${error.message}`);
    }
}

// CLI Execution
const args = process.argv.slice(2);
if (args.length !== 1) {
    console.log(`
🚕 Haram Taxi Competitor Web Scraper
Usage: node scraper-bot.mjs <URL>
Example: node scraper-bot.mjs https://www.wellcarelimosaudi.com/
`);
    process.exit(1);
}

scrapeCompetitor(args[0]);
