import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

// ---------------------------------------------------------
// Haram Taxi - Massive TripAdvisor Saudi Miner 🤖
// Extracts full conversations, routes, posts, and pricing!
// Usage: node scripts/tripadvisor-miner.mjs "URL"
// ---------------------------------------------------------

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

async function mineTripAdvisor(targetUrl) {
    console.log(`\n🦉 Haram Taxi TripAdvisor Miner Initiated...`);
    console.log(`📡 Target: ${targetUrl}`);

    let cheerio, axios, https;
    try {
        cheerio = await import('cheerio');
        axios = (await import('axios')).default;
        https = await import('https');
    } catch (e) {
        console.error('\n❌ ERROR: Missing dependencies.');
        console.error('👉 Please run in terminal: npm install cheerio axios');
        process.exit(1);
    }

    const httpsAgent = new https.Agent({ rejectUnauthorized: false });

    try {
        // Fetch raw HTML with extreme browser spoofing to bypass TripAdvisor DataDome
        const response = await axios.get(targetUrl, {
            httpsAgent: httpsAgent,
            headers: {
                'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.51 Safari/537.36',
                'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8',
                'Accept-Language': 'en-US,en;q=0.9',
                'Connection': 'keep-alive',
                'Sec-Fetch-Dest': 'document',
                'Sec-Fetch-Mode': 'navigate',
                'Sec-Fetch-Site': 'none'
            },
            timeout: 15000,
            validateStatus: function (status) {
                return status < 500;
            }
        });

        const $ = cheerio.load(response.data);
        console.log(`✅ Successfully injected into TripAdvisor! Parsing data...`);

        // 1. Get Thread/Topic Title
        const threadTitle = $('h1').text().trim() || $('title').text().trim() || 'TripAdvisor Saudi Thread';

        // 2. Extract ALL Posts/Discussions
        const posts = [];
        // TripAdvisor forum posts usually use these classes or tags
        $('.postBody, .QWeEX, q, [data-test-target="HR_CC_CARD"]').each((i, el) => {
            const text = $(el).text().trim().replace(/\s+/g, ' ');
            if (text.length > 50 && !posts.includes(text)) {
                posts.push(text);
            }
        });

        // Fallback if specific classes fail
        if (posts.length === 0) {
            $('p').each((i, el) => {
                const text = $(el).text().trim().replace(/\s+/g, ' ');
                if (text.length > 80 && !text.includes("Tripadvisor") && !text.includes("Cookie")) {
                    posts.push(text);
                }
            });
        }

        // 3. Extract Route Intelligence & Fares (Looking for Makkah, Madinah, SAR)
        const routesAndPrices = [];
        const keywordRegex = /(makkah|madinah|jeddah|sar|riyal|price|cost|taxi|train|haramain|bus)/i;
        
        posts.forEach(post => {
            if (keywordRegex.test(post)) {
                routesAndPrices.push(post);
            }
        });

        // 4. Generate the Massive Report
        const dateStr = new Date().toISOString().split('T')[0];
        const report = `
# 🦉 TripAdvisor Saudi Miner Report
**Thread:** ${threadTitle}
**URL:** ${targetUrl}
**Scraped On:** ${dateStr}

## 🛣️ Valuable Route & Pricing Intelligence
(Mentions of Makkah, Madinah, Jeddah, Taxi, SAR, Train)
${routesAndPrices.length > 0 ? routesAndPrices.map(r => `> 🚕 *"...${r}..."*`).join('\n\n') : '*No specific route or pricing data found in this thread.*'}

---

## 📝 Full Posts & Conversation Dump
(Raw data from tourists discussing Saudi travel)
${posts.map((p, i) => `**Post ${i+1}:**\n${p}\n`).join('\n')}

---
*Report generated by Haram Taxi Automated TripAdvisor Miner Bot.*
`;

        // 5. Save to file
        const outputDir = path.join(__dirname, 'output');
        if (!fs.existsSync(outputDir)) {
            fs.mkdirSync(outputDir);
        }

        const safeFilename = `tripadvisor_saudi_data_${Date.now()}.md`;
        const outputPath = path.join(outputDir, safeFilename);
        
        fs.writeFileSync(outputPath, report.trim());

        console.log(`\n🎉 MASSIVE DATA EXTRACTION COMPLETE!`);
        console.log(`📊 Extracted ${posts.length} full posts and route details.`);
        console.log(`📄 Check the file: ${outputPath}`);

    } catch (error) {
        console.error(`\n❌ Failed to scrape TripAdvisor: ${error.message}`);
    }
}

// CLI Execution
const args = process.argv.slice(2);
if (args.length !== 1) {
    console.log(`
🦉 Haram Taxi TripAdvisor Miner
Usage: node tripadvisor-miner.mjs "TripAdvisor URL"
Example: node tripadvisor-miner.mjs "https://www.tripadvisor.com/ShowTopic-g293993-i10419-k14316260-Jeddah_airport_to_makkah_hotel-Makkah_Makkah_Province.html"
`);
    process.exit(1);
}

mineTripAdvisor(args[0]);
